const cfg=window.CLIENTFLOW_CONFIG||{};const KEY="clientflow_contacts_v2";const cloudMode=Boolean(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY);const sb=cloudMode?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;let contacts=[];
const $=id=>document.getElementById(id);const els={navItems:document.querySelectorAll(".nav-item"),views:document.querySelectorAll(".view"),pageTitle:$("pageTitle"),addClientBtn:$("addClientBtn"),dialog:$("clientDialog"),form:$("clientForm"),dialogTitle:$("dialogTitle"),closeDialog:$("closeDialog"),cancelBtn:$("cancelBtn"),deleteBtn:$("deleteBtn"),exportBtn:$("exportBtn"),searchInput:$("searchInput"),stageFilter:$("stageFilter"),sourceFilter:$("sourceFilter"),refreshBtn:$("refreshBtn")};
$("modeBanner").textContent=cloudMode?"Cloud mode: public submissions and staff CRM share one database.":"Demo mode: data is stored only in this browser. Add Supabase keys in config.js before publishing the public link.";
function esc(v){return String(v??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[ch]))}
function fmtDate(s){if(!s)return"—";return new Date(s+"T00:00:00").toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"})}
function money(n){return Number(n)>0?"GHS "+Number(n).toLocaleString():"—"}function today(){return new Date().toISOString().slice(0,10)}
function mapCloud(r){return{id:r.id,name:r.name,phone:r.phone,stage:r.stage,source:r.source,campaign:r.campaign||"",interest:r.interest||"",budget:r.budget||0,timeline:r.timeline||"",owner:r.owner||"",followUp:r.follow_up||"",notes:r.notes||"",consent:r.consent,updatedAt:new Date(r.updated_at||r.created_at).getTime()}}
async function load(){if(cloudMode){const{data,error}=await sb.from("leads").select("*").order("updated_at",{ascending:false});if(error){alert("Could not load cloud leads: "+error.message);return}contacts=(data||[]).map(mapCloud)}else contacts=JSON.parse(localStorage.getItem(KEY)||"[]");render()}
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(contacts))}
function setView(v){els.navItems.forEach(b=>b.classList.toggle("active",b.dataset.view===v));els.views.forEach(x=>x.classList.remove("active"));$(v+"View").classList.add("active");els.pageTitle.textContent=v==="dashboard"?"Dashboard":v==="clients"?"All Contacts":"Follow-ups";render()}
els.navItems.forEach(b=>b.addEventListener("click",()=>setView(b.dataset.view)));document.querySelectorAll("[data-go]").forEach(b=>b.addEventListener("click",()=>setView(b.dataset.go)));
function openNew(){els.form.reset();$("clientId").value="";$("stage").value="Enquirer";$("owner").value=cfg.DEFAULT_OWNER||"Sales Team";els.dialogTitle.textContent="Add Contact";els.deleteBtn.classList.add("hidden");els.dialog.showModal()}
function openEdit(id){const c=contacts.find(x=>String(x.id)===String(id));if(!c)return;els.dialogTitle.textContent="Edit Contact";els.deleteBtn.classList.remove("hidden");["name","phone","stage","source","interest","budget","timeline","owner","followUp","notes"].forEach(k=>$(k).value=c[k]??"");$("clientId").value=c.id;els.dialog.showModal()}window.openEdit=openEdit;
els.addClientBtn.addEventListener("click",openNew);els.closeDialog.addEventListener("click",()=>els.dialog.close());els.cancelBtn.addEventListener("click",()=>els.dialog.close());els.refreshBtn.addEventListener("click",load);
els.form.addEventListener("submit",async e=>{e.preventDefault();const id=$("clientId").value;const rec={name:$("name").value.trim(),phone:$("phone").value.trim(),stage:$("stage").value,source:$("source").value.trim(),interest:$("interest").value.trim(),budget:Number($("budget").value||0),timeline:$("timeline").value,owner:$("owner").value.trim(),follow_up:$("followUp").value||null,notes:$("notes").value.trim()};
if(cloudMode){let q=id?sb.from("leads").update(rec).eq("id",id):sb.from("leads").insert([rec]);const{error}=await q;if(error){alert(error.message);return}els.dialog.close();await load()}else{const local={...rec,followUp:rec.follow_up||"",id:id||crypto.randomUUID(),updatedAt:Date.now()};delete local.follow_up;const i=contacts.findIndex(x=>x.id===id);if(i>=0)contacts[i]=local;else contacts.unshift(local);saveLocal();els.dialog.close();render()}});
els.deleteBtn.addEventListener("click",async()=>{const id=$("clientId").value;if(!id||!confirm("Delete this contact?"))return;if(cloudMode){const{error}=await sb.from("leads").delete().eq("id",id);if(error){alert(error.message);return}els.dialog.close();await load()}else{contacts=contacts.filter(x=>x.id!==id);saveLocal();els.dialog.close();render()}});
[els.searchInput,els.stageFilter,els.sourceFilter].forEach(x=>x.addEventListener("input",renderClients));
function renderDashboard(){const total=contacts.length,c=s=>contacts.filter(x=>x.stage===s).length,due=contacts.filter(x=>x.followUp&&x.followUp<=today()).length;$("metricTotal").textContent=total;$("metricEnquirers").textContent=c("Enquirer");$("metricPotential").textContent=c("Potential Client");$("metricClients").textContent=c("Client");$("metricDue").textContent=due;
$("pipelineBars").innerHTML=["Enquirer","Potential Client","Client"].map(s=>{const n=c(s),p=total?Math.round(n/total*100):0;return`<div class="pipeline-row"><span>${s}</span><div class="bar-track"><div class="bar-fill" style="width:${p}%"></div></div><strong>${n}</strong></div>`}).join("");
const sc={};contacts.forEach(x=>sc[x.source||"Unknown"]=(sc[x.source||"Unknown"]||0)+1);$("sourceList").innerHTML=Object.entries(sc).sort((a,b)=>b[1]-a[1]).map(([s,n])=>`<div class="source-row"><span>${esc(s)}</span><strong>${n}</strong></div>`).join("")||`<div class="empty">No acquisition data yet.</div>`;
const recent=[...contacts].sort((a,b)=>b.updatedAt-a.updatedAt).slice(0,6);$("recentTable").innerHTML=recent.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.phone)}</td><td>${esc(c.interest||"—")}</td><td><span class="stage-pill">${esc(c.stage)}</span></td><td>${esc(c.source)}</td><td>${fmtDate(c.followUp)}</td></tr>`).join("")||`<tr><td colspan="6" class="empty">No contacts yet.</td></tr>`;
const sources=[...new Set(contacts.map(c=>c.source).filter(Boolean))].sort();els.sourceFilter.innerHTML=`<option value="">All sources</option>`+sources.map(s=>`<option>${esc(s)}</option>`).join("")}
function filtered(){const q=els.searchInput.value.trim().toLowerCase(),stage=els.stageFilter.value,source=els.sourceFilter.value;return contacts.filter(c=>[c.name,c.phone,c.interest,c.notes,c.owner].join(" ").toLowerCase().includes(q)&&(!stage||c.stage===stage)&&(!source||c.source===source))}
function renderClients(){const rows=filtered();$("clientsTable").innerHTML=rows.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.phone)}</td><td>${esc(c.interest||"—")}</td><td><span class="stage-pill">${esc(c.stage)}</span></td><td>${esc(c.source)}</td><td>${money(c.budget)}</td><td>${fmtDate(c.followUp)}</td><td>${esc(c.owner||"—")}</td><td><button class="row-action" onclick="openEdit('${c.id}')">Edit</button></td></tr>`).join("")||`<tr><td colspan="9" class="empty">No matching contacts.</td></tr>`}
function cards(items,due){return items.map(c=>`<div class="followup-card"><div><strong>${esc(c.name)} · ${esc(c.phone)}</strong><span>${esc(c.interest||"No product noted")} · ${esc(c.stage)} · ${fmtDate(c.followUp)}</span></div><button class="secondary-btn" onclick="openEdit('${c.id}')">Open</button></div>`).join("")||`<div class="empty">${due?"Nothing due right now.":"No upcoming follow-ups scheduled."}</div>`}
function renderFollowups(){const t=today();$("dueFollowups").innerHTML=cards(contacts.filter(c=>c.followUp&&c.followUp<=t).sort((a,b)=>a.followUp.localeCompare(b.followUp)),true);$("upcomingFollowups").innerHTML=cards(contacts.filter(c=>c.followUp&&c.followUp>t).sort((a,b)=>a.followUp.localeCompare(b.followUp)),false)}
function render(){renderDashboard();renderClients();renderFollowups()}
els.exportBtn.addEventListener("click",()=>{const h=["Name","Phone","Stage","Source","Campaign","Interest","Budget","Timeline","Owner","Follow-up","Notes"],r=contacts.map(c=>[c.name,c.phone,c.stage,c.source,c.campaign,c.interest,c.budget,c.timeline,c.owner,c.followUp,c.notes]),e=v=>`"${String(v??"").replaceAll('"','""')}"`,csv=[h,...r].map(x=>x.map(e).join(",")).join("\n"),u=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8;"})),a=document.createElement("a");a.href=u;a.download="clientflow_contacts.csv";a.click();URL.revokeObjectURL(u)});
load();
